# Generated by Django 6.0.4 on 2026-05-06 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_messages', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_user_messages', models.IntegerField(default=0)),
                ('total_bot_responses', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('total_words_generated', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('human_escalations', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Uso Diario',
                'verbose_name_plural': 'Usos Diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('bot', 'Chatbot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('needs_human', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_api.conversationlog')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='chatbot_api_timesta_ef3f59_idx'), models.Index(fields=['role'], name='chatbot_api_role_684f56_idx')],
            },
        ),
    ]
